### PR TITLE
Spiced up the readme.

### PR DESCRIPTION
**Pull request by Pysis868**
*chef's kiss*

### CODE REVIEW

**Review by blazejmg917 — COMMENTED** [review]
good

**Review by Flyer95 — APPROVED** [review]
This is top-notch stuff

**Review by willcarpenter3 — APPROVED** [review]
beautiful

**Comment by Flyer95** [comment]
well said

**Comment by audinpex** [comment]
I approve this pull request. Spice up is good.

**Comment by Ankhman12** [comment]
Noice

**Comment by iSkytran** [comment]
Seems legit

**Comment by Malmadork** [comment]
poggers

**Comment by Crystalwolf953** [comment]
Looking good

**Comment by audinpex** [comment]
This is good

**Review by iSkytran — APPROVED** [review]

**Review by blazejmg917 — APPROVED** [review]
ey it lookin good

**Review by Crystalwolf953 — APPROVED** [review]

**Review by Malmadork — APPROVED** [review]
pretty poggers.

**Comment by jojods1125** [comment]
good

**Review by Ankhman12 — APPROVED** [review]
Looks good

**Review by audinpex — APPROVED** [review]

**Comment by Pysis868** [comment]
yolo

**Pull request merged**
